version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: "core.digicre.net -> http://web:80, bolide.digicre.net -> http://bolide_frontend:80"
      STAGE: "production"
    restart: always
    networks:
      - https_network

networks:
  https_network:
    external: true
